{ "value": "ach", "name": "Acholi "},
{ "value": "af", "name": "Afrikaans "},
{ "value": "sq", "name": "Albanian  — Shqip"},
{ "value": "ar", "name": "Arabic  — عربي"},
{ "value": "an", "name": "Aragonese  — aragonés"},
{ "value": "hy-AM", "name": "Armenian  — Հայերեն"},
{ "value": "ast", "name": "Asturian  — Asturianu"},
{ "value": "az", "name": "Azerbaijani  — Azərbaycanca"},
{ "value": "eu", "name": "Basque  — Euskara"},
{ "value": "be", "name": "Belarusian  — Беларуская"},
{ "value": "bn", "name": "Bengali  — বাংলা"},
{ "value": "bs", "name": "Bosnian  — Bosanski"},
{ "value": "br", "name": "Breton  — Brezhoneg"},
{ "value": "bg", "name": "Bulgarian  — Български"},
{ "value": "my", "name": "Burmese  — မြန်မာဘာသာ"},
{ "value": "ca", "name": "Catalan  — Català"},
{ "value": "ca-valencia", "name": "Catalan (Valencian)  — Català (Valencià)"},
{ "value": "zh-CN", "name": "Chinese (Simplified)  — 中文 (简体)"},
{ "value": "zh-TW", "name": "Chinese (Traditional)  — 正體中文 (繁體)"},
{ "value": "hr", "name": "Croatian  — Hrvatski"},
{ "value": "cs", "name": "Czech  — Čeština"},
{ "value": "da", "name": "Danish  — Dansk"},
{ "value": "nl", "name": "Dutch  — Nederlands"},
{ "value": "en-GB", "name": "English (British) "},
{ "value": "en-CA", "name": "English (Canadian) "},
{ "value": "en-US": "name": "English (US)"},
{ "value": "eo", "name": "Esperanto "},
{ "value": "et", "name": "Estonian  — Eesti keel"},
{ "value": "fi", "name": "Finnish  — suomi"},
{ "value": "fr", "name": "French  — Français"},
{ "value": "fy-NL", "name": "Frisian  — Frysk"},
{ "value": "fur", "name": "Friulian  — Furlan"},
{ "value": "ff", "name": "Fulah  — Pulaar-Fulfulde"},
{ "value": "gd", "name": "Gaelic (Scotland)  — Gàidhlig"},
{ "value": "gl", "name": "Galician  — Galego"},
{ "value": "ka", "name": "Georgian  — ქართული"},
{ "value": "de", "name": "German  — Deutsch"},
{ "value": "el", "name": "Greek  — Ελληνικά"},
{ "value": "gn", "name": "Guarani  — Avañe'ẽ"},
{ "value": "gu-IN", "name": "Gujarati (India)  — ગુજરાતી (ભારત)"},
{ "value": "he", "name": "Hebrew  — עברית"},
{ "value": "hi-IN", "name": "Hindi (India)  — हिन्दी (भारत)"},
{ "value": "hu", "name": "Hungarian  — magyar"},
{ "value": "is", "name": "Icelandic  — íslenska"},
{ "value": "id", "name": "Indonesian  — Bahasa Indonesia"},
{ "value": "ia", "name": "Interlingua "},
{ "value": "ga-IE", "name": "Irish  — Gaeilge"},
{ "value": "it", "name": "Italian  — Italiano"},
{ "value": "ja", "name": "Japanese  — 日本語"},
{ "value": "kab", "name": "Kabyle  — Taqbaylit"},
{ "value": "kn", "name": "Kannada  — ಕನ್ನಡ"},
{ "value": "cak", "name": "Kaqchikel  — Maya Kaqchikel"},
{ "value": "kk", "name": "Kazakh  — Қазақ"},
{ "value": "km", "name": "Khmer  — ខ្មែរ"},
{ "value": "ko", "name": "Korean  — 한국어"},
{ "value": "lv", "name": "Latvian  — Latviešu"},
{ "value": "lij", "name": "Ligurian  — Ligure"},
{ "value": "lt", "name": "Lithuanian  — Lietuvių"},
{ "value": "dsb", "name": "Lower Sorbian  — Dolnoserbšćina"},
{ "value": "mk", "name": "Macedonian  — Македонски"},
{ "value": "ms", "name": "Malay  — Melayu"},
{ "value": "mr", "name": "Marathi  — मराठी"},
{ "value": "ne-NP", "name": "Nepali  — नेपाली"},
{ "value": "nb-NO", "name": "Norwegian (Bokmål)  — Norsk bokmål"},
{ "value": "nn-NO", "name": "Norwegian (Nynorsk)  — Norsk nynorsk"},
{ "value": "oc", "name": "Occitan (Lengadocian)  — occitan (lengadocian)"},
{ "value": "fa", "name": "Persian  — فارسی"},
{ "value": "pl", "name": "Polish  — Polski"},
{ "value": "pt-BR", "name": "Portuguese (Brazilian)  — Português (do&nbsp;Brasil)"},
{ "value": "pt-PT", "name": "Portuguese (Portugal)  — Português (Europeu)"},
{ "value": "pa-IN", "name": "Punjabi (India)  — ਪੰਜਾਬੀ (ਭਾਰਤ)"},
{ "value": "ro", "name": "Romanian  — Română"},
{ "value": "rm", "name": "Romansh  — rumantsch"},
{ "value": "ru", "name": "Russian  — Русский"},
{ "value": "sc", "name": "Sardinian  — Sardu"},
{ "value": "sco", "name": "Scots "},
{ "value": "sr", "name": "Serbian  — Српски"},
{ "value": "szl", "name": "Silesian  — Ślōnsko godka"},
{ "value": "si", "name": "Sinhala  — සිංහල"},
{ "value": "sk", "name": "Slovak  — slovenčina"},
{ "value": "sl", "name": "Slovenian  — Slovenščina"},
{ "value": "son", "name": "Songhai  — Soŋay"},
{ "value": "es-AR", "name": "Spanish (Argentina)  — Español (de Argentina)"},
{ "value": "es-CL", "name": "Spanish (Chile)  — Español (de Chile)"},
{ "value": "es-MX", "name": "Spanish (Mexico)  — Español (de México)"},
{ "value": "es-ES", "name": "Spanish (Spain)  — Español (de España)"},
{ "value": "sv-SE", "name": "Swedish  — Svenska"},
{ "value": "tl", "name": "Tagalog "},
{ "value": "tg", "name": "Tajik  — Тоҷикӣ"},
{ "value": "ta", "name": "Tamil  — தமிழ்"},
{ "value": "te", "name": "Telugu  — తెలుగు"},
{ "value": "th", "name": "Thai  — ไทย"},
{ "value": "trs", "name": "Triqui "},
{ "value": "tr", "name": "Turkish  — Türkçe"},
{ "value": "uk", "name": "Ukrainian  — Українська"},
{ "value": "hsb", "name": "Upper Sorbian  — Hornjoserbsce"},
{ "value": "ur", "name": "Urdu  — اُردو"},
{ "value": "uz", "name": "Uzbek  — Oʻzbek tili"},
{ "value": "vi", "name": "Vietnamese  — Tiếng Việt"},
{ "value": "cy", "name": "Welsh  — Cymraeg"},
{ "value": "xh", "name": "Xhosa  — isiXhosa"},